# Site settings
title: Vasilii Triandafilidi
header-img: img/home-bg.jpg
email: vasiliy.triandafilidi@gmail.com
copyright_name: Vasilii Triandafilidi personal blog
description: "Personal blog on learning and entrepreneurship"
# baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://bazilevs31.github.io"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
